# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainDialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(594, 557)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayoutLogo = QtWidgets.QGridLayout()
        self.gridLayoutLogo.setObjectName("gridLayoutLogo")
        self.labelLogo = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.labelLogo.sizePolicy().hasHeightForWidth())
        self.labelLogo.setSizePolicy(sizePolicy)
        self.labelLogo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLogo.setObjectName("labelLogo")
        self.gridLayoutLogo.addWidget(self.labelLogo, 0, 2, 1, 1)
        self.labelConverter = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.labelConverter.sizePolicy().hasHeightForWidth())
        self.labelConverter.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.labelConverter.setFont(font)
        self.labelConverter.setAlignment(QtCore.Qt.AlignCenter)
        self.labelConverter.setObjectName("labelConverter")
        self.gridLayoutLogo.addWidget(self.labelConverter, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayoutLogo)
        self.gridLayoutCurrency = QtWidgets.QGridLayout()
        self.gridLayoutCurrency.setObjectName("gridLayoutCurrency")
        self.labelReference = QtWidgets.QLabel(Dialog)
        self.labelReference.setObjectName("labelReference")
        self.gridLayoutCurrency.addWidget(self.labelReference, 0, 0, 1, 1)
        self.comboBoxReferenceCurrency = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxReferenceCurrency.sizePolicy().hasHeightForWidth())
        self.comboBoxReferenceCurrency.setSizePolicy(sizePolicy)
        self.comboBoxReferenceCurrency.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBoxReferenceCurrency.setObjectName("comboBoxReferenceCurrency")
        self.comboBoxReferenceCurrency.addItem("")
        self.comboBoxReferenceCurrency.addItem("")
        self.comboBoxReferenceCurrency.addItem("")
        self.gridLayoutCurrency.addWidget(self.comboBoxReferenceCurrency, 0, 1, 1, 1)
        self.labelUSD = QtWidgets.QLabel(Dialog)
        self.labelUSD.setObjectName("labelUSD")
        self.gridLayoutCurrency.addWidget(self.labelUSD, 1, 0, 1, 1)
        self.lineEditUSD = QtWidgets.QLineEdit(Dialog)
        self.lineEditUSD.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEditUSD.setObjectName("lineEditUSD")
        self.gridLayoutCurrency.addWidget(self.lineEditUSD, 1, 1, 1, 2)
        self.labelPHP = QtWidgets.QLabel(Dialog)
        self.labelPHP.setObjectName("labelPHP")
        self.gridLayoutCurrency.addWidget(self.labelPHP, 2, 0, 1, 1)
        self.lineEditPHP = QtWidgets.QLineEdit(Dialog)
        self.lineEditPHP.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEditPHP.setObjectName("lineEditPHP")
        self.gridLayoutCurrency.addWidget(self.lineEditPHP, 2, 1, 1, 2)
        self.labelIDR = QtWidgets.QLabel(Dialog)
        self.labelIDR.setObjectName("labelIDR")
        self.gridLayoutCurrency.addWidget(self.labelIDR, 3, 0, 1, 1)
        self.lineEditIDR = QtWidgets.QLineEdit(Dialog)
        self.lineEditIDR.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEditIDR.setObjectName("lineEditIDR")
        self.gridLayoutCurrency.addWidget(self.lineEditIDR, 3, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayoutCurrency.addItem(spacerItem, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayoutCurrency)
        self.horizontalLayoutButton = QtWidgets.QHBoxLayout()
        self.horizontalLayoutButton.setObjectName("horizontalLayoutButton")
        self.pushButtonConfigure = QtWidgets.QPushButton(Dialog)
        self.pushButtonConfigure.setObjectName("pushButtonConfigure")
        self.horizontalLayoutButton.addWidget(self.pushButtonConfigure)
        self.pushButtonLoadRates = QtWidgets.QPushButton(Dialog)
        self.pushButtonLoadRates.setObjectName("pushButtonLoadRates")
        self.horizontalLayoutButton.addWidget(self.pushButtonLoadRates)
        self.verticalLayout.addLayout(self.horizontalLayoutButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelLogo.setText(_translate("Dialog", "Logo"))
        self.labelConverter.setText(_translate("Dialog", "Currency Converter"))
        self.labelReference.setText(_translate("Dialog", "Reference"))
        self.comboBoxReferenceCurrency.setItemText(0, _translate("Dialog", "USD"))
        self.comboBoxReferenceCurrency.setItemText(1, _translate("Dialog", "PHP"))
        self.comboBoxReferenceCurrency.setItemText(2, _translate("Dialog", "IDR"))
        self.labelUSD.setText(_translate("Dialog", "USD"))
        self.labelPHP.setText(_translate("Dialog", "PHP"))
        self.labelIDR.setText(_translate("Dialog", "IDR"))
        self.pushButtonConfigure.setText(_translate("Dialog", "Configure"))
        self.pushButtonLoadRates.setText(_translate("Dialog", "Load Rates"))
